"""npcforge — NPC dialogue + bark libraries + cast generation, agent-ready.

v0.3.0 introduces a tools layer (:mod:`npcforge.tools`) with typed Pydantic
contracts. Every capability — world-profile inference, NPC generation, the
walk-up/bark pipeline — is exposed as a single async function that the CLI
and the MCP server both call. Agent frameworks can import and register
these directly.
"""

from .generation import (
    append_bark_triggers_to_yaml,
    append_intents_to_yaml,
    append_npcs_to_yaml,
    gen_barks as gen_barks_impl,
    gen_intents as gen_intents_impl,
    gen_npcs as gen_npcs_impl,
    gen_repeat_greeting_node as gen_repeat_greeting_node_impl,
    gen_time_of_day_greetings as gen_time_of_day_greetings_impl,
    resolve_stubs as resolve_stubs_impl,
)
from .lint import ForbiddenHit, LintReport, lint_barks, lint_text, lint_walk_up_branches
from .pipeline import (
    Mode,
    generate_barks_for_npc_trigger,
    generate_branch,
    generate_for_npc,
    run_all,
)
from .prompts import (
    build_bark_respondent_prompt,
    build_npc_respondent_prompt,
    render_character_sheet,
    render_player_intent,
)
from .schemas import (
    BarkLine,
    BarksConfig,
    BarkTrigger,
    KnowledgeItem,
    NpcBarkConfig,
    NpcSheet,
    NpcStub,
    PlayerIntent,
    Relationship,
    StateEvolution,
    VocabularyCeiling,
    load_barks_config,
    load_intents,
    load_npcs,
    load_npcs_with_stubs,
    load_world_bible,
    resolve_intents_for_npc,
)
from .tools import (
    TOOL_REGISTRY,
    BuildPipelineInput,
    BuildPipelineOutput,
    EngineSyncInput,
    EngineSyncOutput,
    GenBarksInput,
    GenBarksOutput,
    GenGreetingsInput,
    GenGreetingsOutput,
    GenIntentsInput,
    GenIntentsOutput,
    GenNpcsInput,
    GenNpcsOutput,
    GenRepeatGreetingInput,
    GenRepeatGreetingOutput,
    InferWorldProfileInput,
    InferWorldProfileOutput,
    ListNpcsInput,
    ListNpcsOutput,
    ResolveStubsInput,
    ResolveStubsOutput,
    ShowWorldProfileInput,
    ShowWorldProfileOutput,
    ToolSpec,
    build_pipeline,
    engine_sync,
    gen_barks,
    gen_greetings,
    gen_intents,
    gen_npcs,
    gen_repeat_greeting,
    infer_world_profile,
    list_npcs,
    list_tool_specs,
    resolve_stubs,
    show_world_profile,
)
from .audio import (
    LineRecord,
    canonicalise_text,
    count_syllables,
    estimate_duration_seconds,
    infer_emotion,
    line_id,
    read_lines_csv,
    write_lines_csv,
)
from .engines import (
    EngineAdapter,
    SyncAction,
    SyncMarker,
    SyncResult,
    UnityAdapter,
    UnrealAdapter,
    get_adapter,
    marker_path_for,
    supported_engines,
)
from .manifest import (
    BarkTriggerEntry,
    LinesExport,
    LintSummary,
    Manifest,
    NpcEntry,
    NpcWalkUpEntry,
    WorldEntry,
)
from .play import (
    YarnLine,
    YarnNode,
    YarnOption,
    parse_yarn,
    play_barks,
    play_greetings,
    play_repeat_greeting,
    play_walk_up,
    render_all_branches,
    render_barks,
    render_branch,
    render_enum_variants,
    render_visit_variants,
)
from .state import (
    ProjectVariable,
    VariablesConfig,
    VariableType,
    format_variables_for_prompt,
    load_variables,
    yarn_declare_block,
    yarn_literal,
)
from .validate import CompileResult, compile_yarn_files, ysc_available
from .voice_score import score_voice_consistency
from .world_profile import (
    WorldProfile,
    cache_path_for,
    format_profile_for_prompt,
    load_cached_profile,
    save_profile,
)
from .yarn import (
    Branch,
    DialogTurn,
    bark_node_title,
    greeting_node_title,
    render_bark_node,
    render_greetings_node,
    render_repeat_greeting_node,
    render_world_start_node,
    render_yarn_branch,
    render_yarn_node_for_npc,
    repeat_greeting_node_title,
    yarn_escape_line,
    yarn_safe_title,
)

__version__ = "0.8.1"

__all__ = [
    # Version
    "__version__",
    # Schemas
    "NpcSheet",
    "NpcStub",
    "PlayerIntent",
    "Relationship",
    "KnowledgeItem",
    "StateEvolution",
    "VocabularyCeiling",
    "BarkLine",
    "BarkTrigger",
    "NpcBarkConfig",
    "BarksConfig",
    "Branch",
    "DialogTurn",
    "ForbiddenHit",
    "LintReport",
    "CompileResult",
    "Mode",
    "WorldProfile",
    # Loaders
    "load_npcs",
    "load_npcs_with_stubs",
    "load_intents",
    "load_barks_config",
    "load_world_bible",
    "resolve_intents_for_npc",
    "load_cached_profile",
    "save_profile",
    "cache_path_for",
    "format_profile_for_prompt",
    # Tools layer (agent contracts)
    "TOOL_REGISTRY",
    "ToolSpec",
    "list_tool_specs",
    "InferWorldProfileInput",
    "InferWorldProfileOutput",
    "ShowWorldProfileInput",
    "ShowWorldProfileOutput",
    "ListNpcsInput",
    "ListNpcsOutput",
    "GenNpcsInput",
    "GenNpcsOutput",
    "GenIntentsInput",
    "GenIntentsOutput",
    "GenBarksInput",
    "GenBarksOutput",
    "ResolveStubsInput",
    "ResolveStubsOutput",
    "BuildPipelineInput",
    "BuildPipelineOutput",
    "infer_world_profile",
    "show_world_profile",
    "list_npcs",
    "gen_npcs",
    "gen_intents",
    "gen_barks",
    "resolve_stubs",
    "build_pipeline",
    # Generation (library)
    "gen_npcs_impl",
    "gen_intents_impl",
    "gen_barks_impl",
    "resolve_stubs_impl",
    "append_npcs_to_yaml",
    "append_intents_to_yaml",
    "append_bark_triggers_to_yaml",
    # Pipeline
    "generate_branch",
    "generate_for_npc",
    "generate_barks_for_npc_trigger",
    "run_all",
    # Prompts
    "build_npc_respondent_prompt",
    "build_bark_respondent_prompt",
    "render_character_sheet",
    "render_player_intent",
    # Yarn
    "render_world_start_node",
    "render_yarn_branch",
    "render_yarn_node_for_npc",
    "render_bark_node",
    "bark_node_title",
    "yarn_escape_line",
    "yarn_safe_title",
    # Lint
    "lint_text",
    "lint_walk_up_branches",
    "lint_barks",
    # Validate
    "ysc_available",
    "compile_yarn_files",
]
